
  CREATE TABLE "DPS_USER" 
   (	"ID" VARCHAR2(40 BYTE), 
	"LOGIN" VARCHAR2(100 BYTE), 
        "FIRST_NAME" VARCHAR2(40 BYTE),
	"LAST_NAME" VARCHAR2(40 BYTE),
	"EMAIL" VARCHAR2(100 BYTE)
   );


  CREATE UNIQUE INDEX "SYS_C008974" ON "DPS_USER" ("ID"); 
  CREATE UNIQUE INDEX "SYS_C008976" ON "DPS_USER" ("LOGIN");
 
  ALTER TABLE "DPS_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DPS_USER" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "DPS_USER" ADD CHECK (member in (0,1)) ENABLE;
  ALTER TABLE "DPS_USER" ADD PRIMARY KEY ("ID");


 CREATE TABLE "DSS_DPS_EVENT" 
   (	"ID" VARCHAR2(32 BYTE), 
	"TIMESTAMP" DATE, 
	"SESSIONID" VARCHAR2(32 BYTE), 
	"PROFILEID" VARCHAR2(100 BYTE)
   ); ;


  ALTER TABLE "DSS_DPS_EVENT" MODIFY ("ID" NOT NULL ENABLE);


 
CREATE SEQUENCE  "DPS_USER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 7823295 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;